"""
Tests for the basic RAG graph implementation.

These tests verify the functionality of the basic RAG graph pipeline.
"""

import pytest
from unittest.mock import MagicMock, patch
import sys
import os

# Add path to src directory
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../")))

from src.core.graph import build_basic_graph
from src.core.graph.state import RAGState
from src.core.models.document import Document


def test_rag_state_initialization():
    """Test RAGState initialization."""
    state = RAGState(query="test query")
    assert state.query == "test query"
    assert state.normalized_query == ""
    assert len(state.retrieved_documents) == 0
    assert len(state.reranked_documents) == 0
    assert state.context == ""
    assert state.response == ""


@patch("src.core.retrievers.get_retriever")
@patch("src.core.rerankers.get_reranker")
def test_basic_graph_creation(mock_get_reranker, mock_get_retriever):
    """Test basic graph creation."""
    # Setup mock retriever and reranker
    mock_retriever = MagicMock()
    mock_reranker = MagicMock()
    mock_get_retriever.return_value = mock_retriever
    mock_get_reranker.return_value = mock_reranker
    
    # Create graph with mock mode config to prevent factory functions from being called
    graph = build_basic_graph(
        config={
            'mode': 'mock',
            'retriever': {'mock_instance': mock_retriever},
            'reranker': {'mock_instance': mock_reranker}
        }
    )
    
    # Check graph structure (this is a basic smoke test)
    assert graph is not None


def test_graph_executes_all_nodes():
    """Test that the graph executes all nodes in the pipeline."""
    # Create graph in mock mode
    graph = build_basic_graph(config={'mode': 'mock'})
    
    # Execute graph
    state = RAGState(query="test query")
    config = {"configurable": {"thread_id": "test_thread"}}
    result = graph.invoke(state, config)
    
    # Check result state has been processed through all nodes
    assert isinstance(result, dict)
    assert result["query"] == "test query"
    assert result["normalized_query"] == "test query"  # Normalized by first node
    assert len(result["retrieved_documents"]) > 0  # Documents retrieved by second node
    assert len(result["reranked_documents"]) > 0  # Documents reranked by third node
    assert result["context"] != ""  # Context prepared by fourth node
    assert result["response"] != ""  # Response generated by fifth node
    
    # Should contain placeholders in the response
    assert "placeholder response" in result["response"]
    assert "test query" in result["response"] 